app/__init__.py
import os

from flask import Flask


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello, World!'
    
    from .routes import routes
    app.register_blueprint(routes.bp)

    return app

app/routes/routes.py
from flask import (
    Blueprint,
    render_template,
    request,
    send_file,
)
import os

from ..video_downloader import download_video

bp = Blueprint("routes", __name__)
DOWNLOAD_FOLDER = "downloaded_video"


@bp.route("/", methods=("GET", "POST"))
def index():
    if request.method == "POST":
        video_url = request.form["video-url"]
        filename = request.form["name-file-as"]
        title = download_video(video_url, filename)
        return render_template("index.html", video_file=title)

    return render_template("index.html")


@bp.route("/download/<filename>")
def download_file(filename):
    # Ensure the path is absolute and within the expected directory for security
    file_path = os.path.join(os.getcwd(), DOWNLOAD_FOLDER, filename)

    # Use send_file with as_attachment=True to prompt download
    return send_file(file_path, as_attachment=True)

app/templates/base.html
<!doctype html>
<head>
    <title>{% block title %}{% endblock %} - Flask</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<nav>
  <h1>Flask</h1>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
  {% block result %}{% endblock %}
</section>

app/templates/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %} Multi Format Video Downloader {% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="video-url">Video URL </label>
    <input type="url" name="video-url" id="video-url" required>
    <label for="name-file-as">Name File As</label>
    <input name="name-file-as" id="name-file-as">
    <input type="submit" value="Submit">
  </form>
{% endblock %}

{% block result %}
    {% if video_file %}
        <a href="{{ url_for('routes.download_file', filename=video_file) }}" download="optional_filename">
            Download {{ video_file }}
        </a>
    {% endif %}
{% endblock %}